---
title: "A Study in Spirits"
author: "Zeki Salah"
subtitle: Arthur Conan Doyle’s Linkage of Mormonism, Spiritualism, and the Pursuit
  of Primitive Christianity During His Second Spiritualist Tour of America
output:
  html_document:
    css: spirit.css
  word_document: default
  pdf_document:
    template: spirit.tex
abstract: '*This paper explores Arthur Conan Doyle’s visit to Salt Lake City, Utah
  on his 1923 tour of America during which he proslytized Spiritualism. By reading
  local reports of Doyle’s tour, his travelogue, and transcripts of his speeches,
  I argue that Doyle presented Spiritualism as restorationist form of Christianity
  akin to Mormonism. I situate my argument against the view that Spiritualists promoted
  their beliefs by claiming to reconcile scientific and religious tensions that characterized
  the turn of the twentieth century. In his Spiritualist rhetoric, Doyle’s engagement
  with a diversity of American religious desires that often superseded his intents
  to present the religion as scientific and rational. In Salt Lake City, Doyle appealed
  to a predominantly Mormon audience by focusing on religious similarities between
  Spiritualism and Mormonism and stressing their shared lineage as new religions that
  seek to foster a restoration of “primitive Christianity.” I trace the development
  of Doyle’s interest in Mormonism through an investigation of his first Sherlock
  Holmes story, *A Study in Scarlet*. In *A Study*, Doyle was highly critical of the
  Mormon church hierarchy, but presented Mormonism as having an eclectic combination
  of modern and primitive values that fosters social progression. This notion of Mormonism
  as an innovative hybrid of ideas reappeared in Doyle’s Spiritualist rhetoric as
  he argued that both Spiritualism and Mormonism seek to restore primitive Christian
  practices by looking to otherworldly sources. Despite this positive view of Mormonism,
  Doyle utilized his tour through Salt Lake City to ultimately argue that Spiritualism
  was the superior religious choice. After his tour, Doyle continued to criticize
  the authority of the Mormon priesthood, arguing that it encouraged polygamy and
  excluded outsiders. On the other hand, Doyle proposed that Spiritualism offered
  an egalitarian method of accessing primitive Christian truths, unrestrained by institutionalism
  and offering a clearer path towards social progress.*'
bibliography: Study-in-Spirits.bib
csl: chicago-fullnote-bibliography.csl
theme: null
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \allsectionsfont{\raggedright}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}

```
## The Appeal of Spiritualism: 

On May 11 of 1923, Arthur Conan Doyle set foot in Salt Lake City for the first time in his life. He entered the city with the purpose of proselytizing Spiritualism, which he thought to be the "New Revelation" of the twentieth century. While Conan Doyle's legacy as the creator of Sherlock Holmes often brought recognition and respect to his Spiritualist lectures, Salt Lake City seemed to be the exception. Although he had not visited the city before, Doyle had previously voiced criticisms against the city's predominantly Mormon population in his first Sherlock Holmes novel, *A Study in Scarlet*. In *A Study*, Doyle participated in a broader culture of Mormon sensationalism in Victorian England, but he also wrote positively of Mormon society, attributing the prosperity of the Mormons to their religious eclecticism and their Anglo-Saxon cultural heritage. When promoting Spiritualism in Salt Lake City nearly forty years after writing *A Study*, Doyle continued to focus on Mormonism's eclecticism and its relation to their pursuit of Christian restoration, linking these values with the form of Spiritualism that he proselytized. In so doing, Doyle's Spiritualist rhetoric in Salt Lake City complicates a larger historical narrative which dictates that Spiritualists promoted their beliefs by claiming to reconcile scientific and religious tensions that characterized the turn of the twentieth century. Instead, Doyle's engagement with a Mormonism shows that he often prioritized stressing Spiritualism's shared beliefs and values with other American religions, over his attempts to present the religion as scientific and rational.

Many scholars have attributed the rapid spread of Spiritualism throughout the United States in the nineteenth and twentieth century to a cultural reaction to emerging materialistic worldviews and to major world conflicts that caused massive casualties. In these narratives, Spiritualist rhetoric is often presented as emerging in response to scientific materialism and aiming to provide an empirical and rationalist explanation for otherworldly phenomena. [For examples of historical narratives that frame the development of Spiritualism around modernist crises of see @JOppenheim; also: @FTurner] For instance, in one of the most extensive histories of Spiritualism, *In Search of White Crows*, Robert L. Moore argues that argues that American curiosity in Spiritualism was catalyzed by a yearning for scientific and religious reconciliation:

> Over the past 175 years Spiritualism and then psychical research have offered Americans a ‘reasonable’ solution to the problem of how to accommodate religious and scientific interests.[@WhiteCrows, xii.]  

\noindent By tracing Spiritualist popularity through its ability to relieve scientific and religious tensions, Moore overlooks other aspects of Spiritualism that resonate with its practitioners. By focusing only on the “rational” element of Spiritualist justification, Moore ignores lived religious practices that have historically informed Spiritualist thought and that have permeated through American religious culture.

Viewing Spiritualism as a reaction to the increasing popularity of scientific materialism, to the loses of war, or to disenchantment with modern life has become a pervasive view. Those in favor of this sort of telling of Spiritualist history frequently point to the empirical nature of Spiritualist practices in justifying their view. One frequently cited case is Mary Farrell Bednarowski's examination of nineteenth century Spiritualists' attempts to provide scientific explanations of the afterlife:

> Spiritualism represents a concerted, perhaps even a desperate, effort to reconcile science with religion, to supply those suffering from religious skepticism [with] scientific data, [namely] the spirit manifestations, upon which to base their beliefs in an afterlife.[@Bednarowski, 20.] 

\noindent Associating Spiritualism with empiricism, many scholars see it as an answer to materialistic views that emerged in the mid-nineteenth century and to the losses of the American Civil War and World War One. These histories of Spiritualism tend to trace its popularity as a reaction against major cultural shifts that occurred around the turn of the twentieth century. When the development of biblical archaeology and the theory of evolution brought into question the role of the supernatural in human history, Spiritualism offered empirical evidence of the supernatural.[For an account of how Spiritualism provided empirical evidence in response to a modernist crisis of religion see: @Pimple; also: @FTurner] When massive wars separated millions of people from their families and loved ones, Spiritualism offered the ability to reconnect with the dead.[for an account of how Spiritualism served the needs of those mourning the loss of loved ones following the American Civil War see: @GilpinFaust.] 

This tendency to attribute Spiritualism's popularity with its empirical nature has also affected scholarship on Doyle's Spiritualist career. Michael Saler attributes the popularity of Sherlock Holmes to the character’s ability to answer an intellectual climate of cultural pessimism. Saler argues that the *fin de siècle* was characterized by a cultural desire for “communal beliefs and higher ideals in an age that seemed dominated by positivism and materialism.”[@Saler, 602.]  Saler approaches Spiritualism as a reaction to this desire, writing that it was an effort to escape the “iron cage of rationality” that gripped early twentieth century intellectual culture:

> “Modernity” was widely associated with progress toward the rational and away from the supernatural, and efforts by believers to impart the veneer of scientific respectability to the supernatural was frequently greeted with scepticism if not outright disdain by contemporary commentators. Thus psychical research and spiritualism, both nineteenth century efforts at finding a *via media* between science and religion, tended to be marginalized by established science at the start of the century.[@Saler, 602. (Emphasis added).]

\noindent Saler sees Spiritualism as an attempt to alleviate tension between science and religion, while still showing a commitment to social progress, by providing a scientific or empirical bases for religious phenomena. This analysis of Spiritualism proves to be harmful to Saler's analysis of Doyle as he explains that Doyle’s disenchantment with atheism and a materialist understanding of the world “led him” to explore Spiritualism.[@Saler, 607] This implies that Doyle’s exploration of Spiritualism was solely due to a rejection of materialism and the “iron cage of rationality,” rather than any deeper sort of intellectual influence. In this analysis, Saler focuses solely on Spiritualism and Doyle’s writing within the context of religious crises. However Saler neglects other cultural desires that Doyle and other Spiritualist figures addressed and essentializes Spiritualist rhetoric as merely reactionary toward materialism.

In reality, Spiritualists such as Doyle did make empiricist and rationalist arguments, but this does not mean that they did not simultaneously appeal to range of religious desires which existed prior to the development of scientific or materialist rhetoric. As evidenced by his two-volume *History of Spiritualism*, Doyle was well-read on the values and tenets of Mormonism, Swedenborgianism, Fourierism, Shakerism, Theosophy, and Harmonial Philosophy. All of these traditions had significant followings in the United States while Doyle was speaking; failing to account for them overlooks a large segment of Doyle’s audience. Recognizing that Spiritualist rhetoric can be examined outside of the "modernist crisis" allows for a richer range of interpretation to be explored, including Spiritualism’s appeal to these American religious trends.

Doyle himself acts as a good example of how individuals were drawn to Spiritualism not by its scientific allure, but by the tenets of Spiritualist practitioners. In his 1924 autobiography, *Memories and Adventures*, Doyle provides an account of his disillusionment with Catholic theology and attraction to Spiritualism. He recalls being a boy and looking at a priest in horror who declared “that there was sure damnation for every one outside the Church.” This is a clear critique of the particularist soteriology of Catholicism, as Doyle describes this moment as the "first rift" of a "chasm" that would come to develop between himself and his Jesuit guides.[@Memories, 29.] This section is expressive of the idea that Doyle’s conversion to Spiritualism was based on more than empirically-based evidence of the afterlife being provided, but was also theologically motivated. In contrast to the rift he felt growing between himself and Catholicism, Doyle extols the universal applicability of Spiritualism, claiming that the belief in the "continuity of personality" can be "reconciled with any religion." [@DoyleHist2, 246] Doyle also gives a number of other possible explanations for his conversion from Catholicism, each revealing of his religious beliefs. In defense of his conversion to Spiritualism Doyle also expresses frustrations with organized religion and disbelief in Catholic doctrines of papal infallibility and Immaculate Conception.[See @LessReligious, 121; Doyle also expresses a critique of organized religion in @Memories, 4]  Again, Doyle’s theological criticisms are not driven solely by a desire for “provable” religious beliefs, but also problems with religious authority. It would have been sufficient for him to take a skeptical stance against Catholicism if he were only looking for an empirically-based religion. However, Doyle had an invested interest in the philosophical aspect of Spiritualism that led him towards a range of criticisms against his prior faith. In his 1923 tour of America, Doyle would continue to stress the philosophical aspects of Spiritualism when speaking about the religion.

## Doyle's Second American Adventure:

Following a public conversion in 1916, Doyle went on numerous tours promoting Spiritualism speaking to hundreds of thousands of people. Doyle’s interest in Spiritualist developed almost thirty years before his conversion, which is indicative of his experience with Spiritualist beliefs and practices prior to his conversion. Doyle began investigating psychical phenomena in 1886, and had his first article concerning psychical phenomenon, supporting the possibility of telepathy, published in the psychic periodical *Light* in 1887.[@Memories, 84, 86] In 1916, Doyle announced his conversion to Spiritualism and his desire to proselytize what he called the “New Revelation,” on tours throughout the world.[Doyle referred to the spread of Spiritualism throughout the world as a “New Revelation.” See: @NewRevelation, 40] After thirty years of studying Spiritualism and psychical phenomena, Doyle concluded that Spiritualism was spreading throughout the world as a dispensation intended to restore religion to a kind of “primitive Christianity.” He went on to tour Australia, Africa, America, and Western Europe promoting Spiritualism, and wrote numerous letters to the press defending Spiritualism. [Doyle frequently engaged in polemics with clergy and secular figures, including the Bishop of London in 1919, and the freethinker Joseph McCabe in 1920. @Booth, 316]

Doyle went on two tours of America to promote Spiritualism, in 1922 and 1923. These tours are significant, because they are Doyle’s last Spiritualist tours to be fully recorded in autobiographical works and were widely reported. ^[Doyle recorded his first and second American tours in his books: *Our American Adventure*, and *Our Second American Adventure* respectively. Doyle also went on a Spiritualist tour of the eastern coast of Africa in 1929, that he recorded in his book *Our African Winter*, but there was far less media coverage of this tour making it more difficult to study.] On his American tours, Doyle showcased spirit photographs and lectured on Spiritualist beliefs in the the afterlife. Many newspapers focused particularly on the photographic element of Doyle's tour, emphasizing Doyle's empirical "proof" of Spiritualism [Doyle frequently stated that the empirical evidence provided by spirit photographs, automatic writing, séances, and other practices was secondary to a deeper knowledge of a spiritual existence. He was not particularly attached to providing phenomenal evidence of Spiritualism. He addressed this idea at the beginning of his photographic lectures, stating that “The papers deal always with phenomena. To us [Spiritualists] phenomena are a secondary nature. They are only to call our attention.” However, newspapers such as the *New York Times* frequently made the phenomenal aspect of his lectures central to their coverage of his Spiritualist rhetoric. For instance, in their initial coverage of Doyle's 1923 tour, the *Times* focused predominantly on his spirit photographs and his role in psychical research being conducted by *Scientific American*. See: @PhotographLecture; @BacktoProve]. In this article, I focus on examining Doyle’s rhetoric in Salt Lake City on his second tour of America. This tour marked the end of Doyle’s most extensive series of Spiritualist lectures, after which he reported covering over 50,000 miles and speaking to over a quarter million people, and as such, can be seen as a culmination of his Spiritualist presentation. [@DoyleSecondAdv, 2] I have chosen to focus on Salt Lake City in particular because there was a history of interest in and conflict with Spiritualism in the Mormon Church throughout the nineteenth century that hinged on doctrinal differences rather than perceived tensions between religion and materialism. [Michael Homer has written extensively on the history of Spiritualism and Mormonism in Salt Lake City. See: @HomerDoyleVisit; @HomerSpirNewReli; @HomerSpirAndMorm] I argue, that this led newspapers in Salt Lake City to capture elements of Doyle's lecture that fell outside of the empirical "proof" provided by spirit photographs and to highlight more of the philosophical elements of his Spiritualist rhetoric. Additionally, Doyle's history studying Mormonism for his first Sherlock Holmes novel, *A Study in Scarlet*, as well as the Victorian culture he was immersed in, likely exposed him to the religious similarities between Spiritualism and Mormonism, and led him to focus on these similarities in his Spiritualist rhetoric.

When Doyle entered Salt Lake City to promote his Spiritualist beliefs, he was well aware of the fact that he needed to rely on more than his spirit photographs to win over his predominantly Mormon audience. However, he was well-prepared for this given that he not only possessed a background researching the history of Spiritualism, but also possessed an understanding of Mormon history and theology. Despite his previous criticisms of Mormonism Doyle was warmly received by the Mormon community in Salt Lake City. On May 11, he spoke at the Mormon Tabernacle, which indicates that the Mormon Church was receptive towards his views to the extent to which they provided him with their most important church as a public speaking platform. His presentation had been heavily advertised in local newspapers, and his previous stops on his 1923 tour had also been reported on leading up to this event.^[Doyle’s lecture as advertised from 7 May 1923 to 11 May 1923 in the *Salt Lake Telegram* and from 9 May 1923 to 11 May 1923 in the *Utah Daily Chronicle*.] These factors encouraged a large and attentive audience to attend Doyle’s lecture, with Mormons and non-Mormons alike giving favorable responses. [Homer lists sympathetic reports from *The Salt Lake Tribune*, *The Salt Lake Telegram*, and *Deseret News*. Doyle estimated that at least 5,000 attended his lecture in Salt Lake City. See: @HomerDoyleVisit, 270; @DoyleSecondAdv, 88.]  

Before I discuss this media coverage of Doyle’s visit to Salt Lake City, I will first analyze the historical context in which he was speaking and the way he sees Mormonism as operating within his Spiritualist worldview. In this article, I will focus particularly on how Doyle appealed to elements of religious eclecticism and Restorationism that developed in both Spiritualist and Mormon thought.[Here, Restorationism refers to the belief that Christianity ought to be restored to a purer and more ancient form practiced by the apostolic early church. See: @ChristianChurch, 225] Doyle's knowledge of Mormonism's intellectual history and religious appeal can be uncovered through an investigation of his first Sherlock Holmes story, *A Study in Scarlet*, which was published in 1878. In what follows, I first examine sources that informed Doyle as he wrote *A Study* to provide insight on how Doyle’s early views of Mormonism were informed by sensationalist literature. I then draw from the content of *A Study* to demonstrate that Doyle's criticisms of the Mormon church hierarchy and fascination with Mormon eclecticism were strongly influenced by other Victorian sources. In the final section of this article, I examine newspaper coverage of Doyle's visit to Salt Lake City, as well as his own travelogue, to show continuity in his feelings about Mormonism as he continued to express worries about authoritative clergy, the exclusion of non-believers, and a lack of adherence to Victorian sensibilities. However, in Salt Lake City, Doyle diluted his criticisms of Mormonism and ultimately presented Mormonism as reconcilable with Spiritualism, with both religions sharing common desires for a restoration of primitive Christianity and cultural eclecticism.

Doyle spoke about Mormonism differently as he directly addressed a more general audience. Following my analysis of media coverage of Doyle in Utah, I draw from his writings in *Our Second American Adventure*, Doyle's travelogue of his 1923 tour in which he describes his experience touring through Salt Lake City. Here, Doyle addresses a more general audience and discusses what he sees as the merits and deficiencies of Mormonism. As Doyle addresses a non-Mormon audience in *Our Second American Adventure*, he is more transparently supportive of Spiritualism than Mormonism, which is representative of his broader philosophy. Doyle also makes more direct attacks on Mormonism in this work by critically examining the legitimacy of the Book of Mormon, questioning Smith’s capacities as a medium, and disparaging the Mormon priesthood as a institution fostering social regression. I will examine comparisons he makes between the two religions in *Our Second American Adventure* to elucidate how he diluted his Spiritualist thought to better appeal to a Mormon audience when he was in Utah. *Our Second American Adventure* also provides insight into how Doyle aimed to frame Mormonism in relation to Spiritualism while on his tour in order to promote the idea that adopting values integral to Spiritualist beliefs could usher in social progression. 

## Mormonism, Sensationalism, and Eclecticism in Victorian England:

In the mid to late-nineteenth century, the British press persistently criticized Mormonism for its oppressive social structures and lack of civility. Michael Homer, a scholar of early Mormonism, notes that sensationalist pieces concerning Mormonism were very popular in United Kingdom in the 1880s, as Mormon missionaries had been successfully proselytizing the country for forty years and politicians, newspapers, and journalists were paying considerable attention to the movement.[@HomerSpirNewReli, 100] The British press at the time was especially xenophobic towards an influx of Mormon missionaries to England with the *London Quarterly Review* urging for the hanging of Mormon missionaries who they claimed were kidnapping English servant-girls.[@MormonMyth, 160. Arrington and Cornwall cite the *London Quarterly Review* 2 (1884): 115-122.] These depictions of Mormon society were not limited to the yellow press but were also frequently found in more reputable journals such as *Atlantic*, *Harpers*, and *Saturday Review*.[@MormonMyth, 160] Rebecca Cornwall and Leonard Arrington examine sensationalist works that may have influenced Doyle and note that the *London Times* published a report on the latest efforts of the U.S. government to rid Utah of polygamy on March 30, 1886, which was around the time Doyle started writing *A Study in Scarlet*.[@MormonMyth, 161] This report sensationalized conditions in Utah, describing a suppression of dissent and threat of violence by Mormon theocracy, that closely paralleled the setting of the novel.[@MormonMyth, 161] A fascination with the mythology of a Mormon theocracy was not only a popular topic in Britain, but was a topic that Doyle explicitly addressed in *A Study*. 

Both the yellow press and more well-known magazines attacked the tenets of Mormonism and its restorationist principles, or call for a return to a primitive form of Christianity. Sebastian Lecourt indicates that descriptions of Mormon society in this period often focused on their attachment to “primitive” or “premodern” values through fixating on “outward forms” of religiosity and reinstating the “practices of Biblical times.”[@Lecourt, 90] Mormon tithes, laws of health, and adherence to the Sabbath were targeted by British and American media alike, and Doyle later criticized the Mormon priesthood for justifying polygamy through reference to the Old Testament.[@DoyleSecondAdv, 207] Magazines portrayed these practices as a kind of or cultural regression. For example, Charles Marshal of *Fraser’s*, a popular London magazine with a strong Tory slant, called Mormonism: “a huge stride backward in the civilisation of the race,” “a system of priestly tyranny more oppressive than that of Rome” that “renews the visions and miracles of primitive times.”[@TheCharacteristicsofMormonism, 692; @Lecourt, 86] The new religious practices of the Mormons were depicted as not only overly authoritative and violent, but as degeneration of the social progress the British had encouraged throughout the world. 

However, as news of Utah’s quick development spread to England in the 1870s, sensationalist narratives quickly shifted to claim the Mormon’s successes as an indication of what Doyle would go on to refer to as “Anglo-Saxon tenacity” in *A Study*.[@DoyleStudy, 79; @Lecourt, 86.] Lecourt writes that this innovation came with the development of the transcontinental railroad, which allowed middle-class tourists and travel writers to visit Salt Lake City.[@Lecourt, 92] The quick industrial development of Salt Lake City brought to light a tension in the English conception of Mormonism: how could the Mormons, a people tied to primitive religious beliefs and social structures, have brought forth modern social developments so quickly? In writing *A Study*, this question operated as a subplot for Doyle as he praised the virtues of Mormon settlerism while also presenting Salt Lake City as controlled by a repressive theocracy.[@Lecourt, 97] Lecourt notes that Doyle’s Brigham Young projects a model image of suburban civilization: “In the town, streets and squares sprang up, as if by magic. In the country, there was draining and hedging, planting and clearing, until the next summer saw the whole country golden with the wheat crop.”[@DoyleStudy, 67; @Lecourt, 96-97] In *A Study*, Mormon society is portrayed by Doyle as developing so quickly that the agents who plan, plant, and build, are conceived of metaphorically as magical forces. Yet, despite his descriptions of extraordinary social progression, Doyle still drew from sensationalized sources in describing Mormon religious structures and leveled harsh criticisms against the religion.

Scholars have traced sensationalist influences upon *A Study* through the content of the novel, sources found in Doyle possession, and the general popularity of sensationalist sources about Mormonism during the time it was written.[@HomerDoyleVisit, 246] Homer argues that Doyle may have chosen Mormon society as the setting for his novel to take advantage of this popularity and to generate income.[@HomerSpirNewReli, 101] The influence of sensationalist literature on Doyle is substantiated by articles found in his personal collections. Rebecca Foster Cornwall and Leonard Arrington note that: 

>In the *International Review* of February 1882, a copy of which was found in Doyle’s papers, an unfriendly report on the Mormons appeared which contained a description of the Great Basin markedly similar to Doyle’s in *Study*.[@MormonMyth, 161; Jack Tracy also reports that a sensationalist autobiography by an ex-Mormon, Fanny Stenhouse, has also been found in Doyle's library collection @ConanDoyleMormons, 15-16; @Stenhouse.] 

\noindent While it is impossible to know the Mormon literature that Doyle was ingesting, other scholars have pointed to sensationalist works that have similar plot structures to *A Study* including a short story by Robert Louis Stevenson titled, “Story of the Destroying Angel.”[@HomerSpirNewReli, 101] Lecourt writes that both stories express a fear of Mormon expansion through portraying “the Mormons’ failure to respect the boundaries of the domestic sphere.”[@Lecourt, 100] In *A Study* Doyle synthesized many similar concerns about Mormon eclecticism and hierarchy. In so doing, he reflected the British press’s: fear of Mormon expansion, portrayal of Mormons as possessing “primitive” values, concern over authoritarianism, and fascination surrounding the relationship between Mormonism and the idea of English globalization. However, upon closer examination of *A Study*, it becomes clear that Doyle's view of Mormon society was not entirely negative, and that he possessed an admiration for Mormon eclecticism that would later manifest in his Spiritualist rhetoric.

## Early Conceptions of Mormonism in *A Study in Scarlet*:

The content of *A Study* is reflective of sensationalized accounts that presented Mormon society as rife with violence and polygamy that was enforced by an authoritative priesthood. In *A Study*, John Ferrier and his adopted daughter Lucy are stranded in a desert and are eventually saved by Brigham Young and a party of Mormons. John then joins the Church of the Latter-Day Saints and subscribes to all tenets of Mormonism except for polygamy, refusing to allow Lucy to marry Mormon polygamists. John and Lucy attempt to escape Mormon society with a non-Mormon coal miner, Jefferson Hope, to whom Lucy becomes engaged. However, they are stopped by the Avenging Angels, members of the Danite band who are described as enforcers of polygamy for the Church hierarchy. The Avenging Angels kill John while Lucy later dies of a broken heart. Twenty years later, Jefferson Hope tracks down and kills two of the Avenging Angels and Sherlock Holmes is called to investigate the case. This story is representative of Doyle’s view of Mormonism and his larger critiques of institutionalized religions being overly authoritative and antagonistic towards outsiders. Doyle presented Mormon society as lacking civility by describing how immoral behaviors, such as polygamy and violence, are enforced through the Church hierarchy. Later, in *Our Second American Adventure*, Doyle acknowledged that he sensationalized the prevalence of violence and polygamy in Mormon society but he maintained his criticism of the church hierarchy and held fast to his historical depiction of the Danite band.[Doyle's account of the Danite band was unsubstantiated. Although Brigham Young did organized a militia to pursue raiders of Mormon cattle and horses, sources which reported on their efforts to capture, kill and torture those who crossed Young fail to produce evidence of such claims. See: @Arrington, 250] 

Despite Doyle’s criticisms of Mormon polygamy and authoritarianism in *A Study*, he also often takes a sympathetic approach to Mormon society in the novel and values what he sees as eclectic beliefs drawn from primitive traditions. He not only voiced appreciation for the industriousness of Mormons, but also acknowledged the religious merits of Mormonism as John Ferrier accepts every tenet of the religion aside of polygamy. He was not alone in voicing this admiration; Lecourt notes that many English writers of the period were fascinated by Mormonism’s variety of religious influences and provides a quote from William Hepworth Dixon’s *New America*:

>[Smith] taught his disciples . . . to extract the grain of good out of every old creed… He took much from Mohammed, more from Paul, most of all from Abraham; but in his free handling of religious notions, he had no scruple about borrowing from the Hindoos, from the Tartars, from the Mohawks. [@NewAmerica, 263; @Lecourt, 101]

\noindent Lecourt argues that English writers of the period, including Doyle, often discussed how foreign and antimodern values helped facilitate English expansion.[@Lecourt, 97]. He notes that Doyle’s value of eclecticism is shown in *A Study* through both Sherlock Holmes and the Mormon Jefferson Hope. Both characters are shown to be cunning through their ability to channel “the forces of the primitive toward modern ends: "Jefferson Hope is repeatedly described as savage-looking and possessing vindictiveness learned from the Indians, while Holmes’ is said to be possessed by “a purely animal lust for the chase.”[@Lecourt, 103-104] This narrative ran counter to the idea that Mormonism's "primitive" inspirations were solely regressive and instead attributed them to be characteristic of Anglo-Saxonism. 

For Doyle, there was a fine line between the innovative bricolage of Holmes and the backwards, yet still pragmatic, religious beliefs of the Mormons. As we will see in Doyle’s 1923 visit to Utah, his belief in eclecticism as an innovative exploration of new and old religious systems plays a strong role in his Spiritualist rhetoric. Eclecticism was not valued by Victorian culture alone, but had also found its way into a plethora of American religious traditions. By the early twentieth century, the stage for religious liberalism and eclecticism was set by the 1893 Chicago World Parliament of Religions and figures such as Thomas Wentworth Higginson and Swami Saradananda.[In his account of the development of religious liberalism in American culture, Leigh Eric Schmidt cites a passage from Saradananda's "The Sympathy of Religions:" "The mission of Vedanta to the West is not to make Christians Hindus, but to make the Christian a better Christian. a Hindu a better Hindu, a Mohammedan a better Mohammedan." This passage is remarkably similar to a passage in Doyle's own *History of Spiritualism*: "The acceptance of the great truths for which psychic science stands should turn an agnostic into a believer in God, should make a Jew a better Jew, a Mohammedan a better Mohammedan, a Christian a better Christian, and certainly a happier and more cheerful one." See: @RestlessSouls, 137; @SympathyofReligions, 318-319; @DoyleHist2, 270.] Eclecticism in America meant not only the innovative combination of old and new which many Victorian writers found characteristic of the Mormons, but also became associated with a pragmatic mixing of religious traditions. When Doyle entered Salt Lake City, he not only appealed to the value in Mormonism's pursuit of a primitive Christianity, but also appealed to the idea that Mormonism and Spiritualism were reconcilable and could be integrated in a way that fostered Christian restoration. 

## Doyle's Linkage of Spiritualism and Mormonism in Salt Lake City:

Analysis of Doyle’s rhetoric is complicated by the fact that copies of his lecture notes in Salt Lake City have not been found or preserved. However, his visit was well documented by local newspapers; on May 11th the *Salt Lake Telegram* published a piece on Doyle featuring quotations from a press conference that occurred shortly after his arrival and on May 12th the *Salt Lake Tribune* reported on the contents of his lecture. These two publications provide some sense of how Doyle targeted his Mormon audience while speaking to the press in Utah. My examination of Doyle’s interaction with the Mormon press draws from an understanding of how Mormonism previously operated within his worldview. Doyle took care to restrain some of his criticisms of Mormon society that he had previously expressed, such as his argument that the Mormon priesthood is an oppressive institution and his depiction of Mormon society as primitive. In this section, media coverage of these two interviews, accompanied by Doyle's lecture notes, will provide insights on aspects of Mormonism that Doyle admired, as well as his criticisms of the religion. I focus particularly on how Doyle spoke about Mormonism's “eclectic” religious views which draw from a variety of religious traditions and its cosmological similarities with Spiritualism. Through this analysis I illustrate that underlying Doyle’s admiration of Mormon society and Spiritualist proselytization is a desire for British cultural imperialism which associates the Anglo-Saxon identity with cultural eclecticism and liberalism and sees the spread of these ideas as integral to social progression

\allsectionsfont{\centering}
### Doyle's Interview with the *Salt Lake Telegram*:

Soon after arriving in Salt Lake City Doyle held his first press conference in the city with the *Salt Lake Telegram*. The article subsequently published by the *Telegram* introduced Doyle’s lecture titled, “Recent Psychic Evidence,” and explained that Doyle had spent over a quarter of a century attempting to collect “tangible proofs of communication with those who have departed this mortal sphere.” [@TelegramMay11] The *Telegram*'s discussion of "spheres" of existence would be familiar to both a Spiritualist and Mormon audience, provided that both religions share a belief in correspondent cosmologies, or the notion that different planes of existence exist outside of, yet correspond with, earthly existence.[This belief is rooted in the influence of Swedenborgianism on Spiritualism and Mormonism. For more information about the commonalities between Swedenborgian and Mormon cosmology see: @DeathinSpiritualismandMormonism; @Refiners] In his opening statements to the *Telegram* Doyle also expressed a deep appreciation for the hospitality of those he has encountered on his tour thus far and noted that people across the United States were becoming increasingly more receptive to his Spiritualist message. He then proclaimed that Spiritualism is the “truth of which the Christian Church is founded,” and emphasized that it would eliminate immorality if accepted throughout the world. [@TelegramMay11] As he focused on the increasing acceptance of his Spiritualist message, Doyle framed it within a progressive view of history that is oriented towards a restoration of Christianity. In Doyle’s concluding statements he commented on the emergence of a “spiritual renaissance” following World War One and argued that the emergence of Spiritualism is the only discernible benefit from the Great War. Throughout his interview with the *Telegram*, Doyle addressed a slew of similarities between Spiritualism and Mormonism, including: beliefs in correspondent cosmologies, an experience of persecution by other religious groups and a desire for the restoration of primitive Christianity.

In his opening statements, Doyle stressed his respect for American religious tolerance. He states: “I want to say, if you will permit me the space, that I deeply appreciate the dignity with which the American people listen to my lecture.” [@TelegramMay11] In this statement Doyle both established his respect for the American people and lauded their ability to listen, tying this to the notion of “dignity.” Doyle saw himself as a representative of Anglo-American relations and viewed both societies as encouraging a progression toward “civility.” [In regard to Doyle’s fascination with American culture, Martin Booth writes: “he became something of an Americanophile, remarking about how American hotels were superior to British ones and how, despite his love of cricket, he thought baseball would supplant it as Britain’s national game.” See: @Booth, 331, 203]  While his portrait of Mormon society in *A Study* was sensationalized, in the novel Doyle also praised the “Anglo-Saxon tenacity” of the Mormons in spreading civilization to remote deserts. By lauding the American people’s “dignified” reception of his Spiritualist message, Doyle is voicing support for what he sees as the progress and civility that is being established by English globalization.

In his *Telegram* interview, Doyle also argued that Spiritualism was becoming increasingly accepted in the United States and suggested that this is indicative of progress being made in the country. He noted that on his current tour, his reception in the States was much more cordial than it was a year ago and repeatedly emphasized Americans’ curiosity and attentiveness, stating that, “everywhere we go I am asked by many earnest truth-hunting persons to give them a word here or there which will assist them in their problems.” [@TelegramMay11] In tying Americans' ability to search for truth with their interest in Spiritualism, Doyle suggested that the truth of Spiritualist phenomena can be found through attentive, rational investigation. As Doyle praised the openness of Americans, and the Mormons in particular, he once again linked social progress with what many writers of the time took to be ideals central to English civilization: liberalism, eclecticism, and a pragmatic mixing of different cultural traditions. [@Lecourt, 101] As Doyle continued to put forth this progressive view of history, he focused on the societal uplift that the spread of Spiritualism will bring and suggested that this progress is propelled by the course of history.

In stating that people’s curiosity about Spiritualism is driven by its ability to “assist them in their problems,” Doyle also emphasized the utility of the religion. Here, Doyle argued that Spiritualism's desirability is linked with an interest in interacting with corresponding worlds for pragmatic purposes. This desire shared among groups that have been categorized by Catherine Albanese as metaphysically religious.[Catherine Albanese discusses the development of "metaphysical religions" in America in her book *A Republic of Mind & Spirit*. This term refers to religions that are especially concerned with the individual's experience of "mind": "Metaphysical forms of religion have privileged the mind in forms that include reason but move beyond it to intuition, clairvoyance, and its relatives such as ‘revelation’ and ‘higher guidance.’ Here versions of a theory of correspondence between worlds prevail. The human world and mind replicate — either ideally, formally, or actually — a larger, often more whole and integrated universe, so that the material world is organically linked to a spiritual one." Albanese contextualizes Mormonism, Spiritualism, and other forms of American religion as metaphysical forms of religion. See: @RepublicofMind, 6] This rhetoric likely resonated with Mormon listeners who not only believed in similar corresponding cosmos and the possibility of other worldly communication, but also historically sought tangible benefits from interactions with these corresponding worlds. [In 1870s, the Godbeite movement formed in Utah as an offshoot of the Church of the Latter-Day Saints that embraced Spiritualism, largely due to similarities in beliefs and practices. The Godbeites utilized a number of Spiritualist practices. One notable minister claimed a group of spirits called "Electrizers" revealed an electric motor that promised humanity a four-hour work day and universal wealth. @WWalker, 307. A broader discussion of similarities in Mormon and Spiritualist beliefs and practices can be found on 317-318 of Walker’s article.] Furthermore, by praising Americans’ desire to search for these pragmatic religious practices on their own, Doyle presented Spiritualism as a kind of democratic approach to religion that does not need to be mediated by a church hierarchy. The truth of Spiritualism can not only be found through anyone’s personal investigation, but can bring practical benefits that do not need to be mediated by any kind of religious hierarchy. 

Doyle's focus on the the growing numbers of Spiritualists in America also served as a critique of his materialist skeptics. He presented Spiritualism as progressive, claiming that it is a truth that will gradually be accepted from generation to generation. Evidence of its truth is that “the world is accepting the possibilities of Spiritualism more of recent years than ever before.”[@TelegramMay11]  Despite the fact that Doyle was targeting his materialist skeptics, this is largely a theological argument, echoing rhetoric that Doyle tour deployed in earlier Spiritualist lectures. By pointing to the growing numbers of Spiritualists, Doyle is arguing that current events suggest that Spiritualism is superior to other religious options. Earlier in his tour, this argument had a strong millennial element, as Doyle argued that the increasing adoption of Spiritualism over other religions, was a sign that Spiritualism came as a divine revelation that would usher in a new and improved society.[In New York City, Doyle uses strong millennialist language, calling Spiritualism "God's most important message to the world, a new revelation" and focusing on materialistic ideologies which he sees as undermining social stability. This kind of rhetoric is evokative of earlier Millenialist figures in American religious history, such as Johnathan Edwards and William Miller. See: @BacktoProve] In Salt Lake City, Doyle even acknowledged a lack of evidence derived from phenomena: “Of course there is still much to be learned, but I believe our children and their children will treat as matters of fact, regular and normal messages with those gone before.”[@TelegramMay11]  While Doyle had faith that Spiritualist phenomena would soon be treated as matter of fact, he conceded that a lack of data weakened his argument and encouraged his audience to pay attention to the religion themselves. Doyle largely turned towards social patterns and historical events to justify his belief; the increasing number of people adopting Spiritualism served as much stronger evidence of its legitimacy as divine revelation than phenomenal proofs.
	
Later in his interview, Doyle transitioned towards a more blatantly religious argument, asserting that the Spiritualist movement is itself a return to primitive Christianity that promises social progress.[Doyle likely recognized that restorationist theology would be particularly resonant with Mormons given that Joseph Smith developed restorationist views alongside other religious experimenters of the nineteenth century including Alexander Campbell, the founder of the Disciples of Christ, and Walter Scott, a reformed Baptist preacher. While other Christian leaders of the time developed their restorationist theology through biblical exegesis, Smith’s theology was informed by his own personal revelations. This makes Smith’s development of a restorationist theology markedly similar to Spiritualist restorationism, which was also informed by personal revelation rather than a scriptural reading. See: @MormonismIntro, 4-5.] He claimed mediumship as synonymous with prophecy and argued that it is the foundation of Christianity:
	
>I am proclaiming the truth upon which the Christian church was founded, and let me tell you when this gets into the hearts of people and takes possession of their understanding there will be no more immorality in the world.[@TelegramMay11]

\noindent Doyle viewed Spiritualism as providing an elevated understanding of the universe and of history that could correct human behavior. Under his view, individuals can progress towards a more refined morality through a knowledge and understanding of other planes of existence, which places their actions within a broader cosmic framework. Doyle viewed continuous revelation as a continued interaction with the “Beyond,” as he details in a 1906 letter to *The Daily Express*:

>I may say that I do not believe that the Divine Message to the human race was delivered once for all two thousand years ago, but I hold that every piece of prose and verse which has in it anything which is helpful to the individual soul is in some sense a message from Beyond–a message which grows and expands as all vital things must do.[@LessReligious, 121.]  

\noindent When Doyle refered to the return to “truth upon which the Christian church was founded,” he was proposing that modern individuals’ revelations should be accepted as possessing the same authority as biblical revelations. By bringing forth the “Christianity” of this teaching Doyle sided with his Mormon audience against mainstream Protestant and Catholic churches on the doctrine of continuous revelation and affirmed their stake to the title of “Christian.” 

As he continued his interview with the *Telegram* Doyle highlighted another similarity between Mormonism and Spiritualism: a belief in the continued existence of a person in other spheres of being after death. Once again, he presented this commonality between the two traditions against mainstream Christian institutions by introducing this teaching after being questioned about a church in the northeastern United States which denied him a speaking platform. When this issue was raised, Doyle responded: “How absurd […] the adoption of this doctrine means the closing out of evil or the agencies throughout which evil works, doesn’t it?”[@TelegramMay11] To Doyle, knowledge of the spirit world is necessary to bring about a moral restoration of society. This is because knowledge of the spirit world serves make people more self-conscious as they become aware that they are being watched by not only God, but by dead relatives as well: “Can you imagine a young man going into a house of ill-fame if he believes the spirit of his dead mother walks with him?”[@TelegramMay11] Doyle proposed that knowledge of the spirit world would encourage people to behave as if they were being watched, which in itself would lead to a more moral society. Doyle affirmed the value in understanding the spirit world through mediumship, rather than continuous revelation, because mediumship promises not only divine guidance for social affairs, but also a constant contact with a higher realm of existence that is spectating human affairs.

In his final statement to the *Telegram*, Doyle provided a narrative of global crisis that is facing society in light of World War One and presented mediumship as a solution to this crisis. Doyle argued that a return to primitive Christianity, or a renewal in the practice of mediumship or continuous revelation, would provide guidance that could prevent future world conflicts. He framed the increasing popularity of Spiritualism with in the context of World War One:

>In the opinion of Sir Arthur, the spiritual renaissance which is so noticeable since the war and which was predicted by many mediums before the war, is really the reason for the war. “I believe this [Spiritualism] is the thing for which the war was fought. The old religions have broken down. This is the only visible benefit from the mighty conflict. All wasted energies of youth, the defeated ambitions, the physical strength destroyed on the battlefield of Europe is beating and breaking down the barriers between the seen and the unseen.”[@TelegramMay11] 

\noindent Doyle saw World War One itself as a kind of “Divine Message,” using the concept of continuous revelation to explain a world crisis that might otherwise seem meaningless. The millions who died in World War One must have served to further religious understanding and to create a more moral society, because otherwise their deaths would be meaningless.[This narrative was likely also very comforting for Doyle, given that his son, Kingsley, died of Spanish influenza, after the Battle of Somme. @TellerOfTales, 348] Doyle focused on the senselessness of war to show the underlying presence and influence of God. By claiming that God is consistently present and active in world events, Doyle provides explanations for both World War One and the spread of Spiritualism linking both events to the idea of a “Divine Message.”

In his closing statement to the *Telegram*, Doyle’s reference to “old religions” breaking down alluded not only to the newness and rising popularity of Spiritualism, but also to its opposition to traditional Christian denominations. Doyle’s Spiritualist teachings promised the possibility of individuals having a personal relationship with the other worldly, that he believed was hindered by religious institutions such as the Catholic, Protestant, and even Mormon churches. Doyle voiced his concerns about organized religion 16 years before converting to Spiritualism. In a letter to *The Scotsman* on October 16, 1900, Doyle wrote:
	
>I regard hard-and-fast dogma of every kind as an unjustifiable and irreligious thing putting assertion in the place of reason, and giving rise to more contention, bitterness, and want of charity than any other influence in human affairs.[@DoyleCatholicChurch, 67-68] 

\noindent Doyle regards Church dogma as irreligious because it is based on historic assertions rather than individuals’ own interactions with the otherworldly. As I will demonstrate, Doyle makes similar critiques of the Mormon church in *Our Second American Adventure*, but neglects to mention them in his addresses to the people of Salt Lake City. By stating that the promulgation of Spiritualist doctrine and the breakdown of historic churches are the reason that the war was fought, Doyle has suggested that Spiritualism is a divinely ordained progression from traditional forms of Christianity. Mormons may be more sympathetic with this rhetoric than Catholics or Protestants, given Mormonism’s similar status as a “new religion” and given its similar conception of continuous revelation, in which individual members of the Church of the Latter-Day Saints have the right to receive revelation for their own responsibilities. However, when Doyle referred to boundaries breaking down between the “seen and unseen” he may have been suggesting to his audience that spiritual messages do not need to be dispersed through an intermediary priesthood. 

### The *Salt Lake City Tribune*'s Coverage of Doyle's Lecture:

On May 12, 1923, the *Salt Lake City Tribune* reported on Doyle’s lecture in the Mormon Tabernacle. The *Tribune*’s coverage of Doyle’s lecture shows him presenting Spiritualism as a supplement to Mormonism that could further restore Mormonism to a state of primitive Christianity. This article provides less direct quotations than Doyle's interview with the *Telegram*, but offers direct coverage from his lecture, making it a valuable resource for examining the extent to which Doyle maintained the rhetorical themes established in the *Telegram*. The *Tribune* opens with Doyle’s description of the spirit world, and then addresses Doyle’s spirit photographs. The article next summarizes Doyle’s development as a Spiritualist, moving from a materialist investigator to Spiritualist proselytizer before quoting a polemic from Doyle against those who do not properly investigate psychical phenomena. As article concludes, it stresses Doyle’s optimistic message that Spiritualism provides in comparison to the “old world” religions of Protestantism and Catholicism. The *Tribune*’s coverage of Doyle’s lecture largely substantiates the presentation of Doyle’s Spiritualist mission offered by the *Telegram* by focusing on Spiritualism’s situation within a progressive understanding of history that culminates in the restoration of primitive Christianity. 

In the *Tribune*’s coverage of Doyle’s lecture, Spiritualism is immediately introduced as an inherently optimistic religion. The article quotes Doyle as having described the spirit world as a “land of realized ideals,” lacking discord and strife and characterized by growth and progress.[@ProofsAdvanced] This phrase echoes the influences of Swedenborg and Davis that Doyle displayed in both his *History of Spiritualism* and *Our Second American Adventure*. As Doyle refers to the spirit world as the “land of realized ideals” he characterizes it as corresponding to life on Earth as individual ambitions and desire continue in and are realized in the spirit world. This view of the afterlife was largely developed from Swedenborg’s understanding of a correspondent afterlife that progressively drew closer to God as individuals passed through it.[@ArcanaCoelesta, 126; @RepublicofMind, 141] Doyle echoed this view in *Our Second American Adventure* as he reported on his wife presenting a similar correspondent progressive cosmology on a radio broadcast in New York City.[@DoyleSecondAdv, 30]

While Doyle’s expression of a progressive and correspondent cosmology was not limited to Salt Lake City, this view of the afterlife shares many similarities with the Mormon view that Doyle most likely recognized. Michael Quinn has argued that Joseph Smith had access to Swedenborg’s writings in Canandaigua and Manchester, New York and makes a case that these writing influenced Smith’s development of a correspondent cosmology in the Book of Mormon.[@EarlyMormonismMagic, 181] Like Swedenborg’s cosmology, Smith proposed the existence of three “degrees of glory” one progresses through in the afterlife. [Smith proposed the existence of Celestial, Terrestrial, and Telestial spheres in the afterlife. @EarlyMormonismMagic, 181] Quinn argues that this similarity suggests influence from Swedenborg in particular because though, “Traditional Christianity divided angels into many categories, a three-tiered classification was rare in traditional Christianity.”[@EarlyMormonismMagic, 182] Most popular Bibles in Smith’s time period would not have had three-tiered classifications of angelic hierarchies, but Swedenborg’s theology not only possessed this similarity, but also incorporated this hierarchy into a progressive and correspondent afterlife. Given that this cosmology is found in the Book of Mormon, amongst other similarities with Swedenborgian and Harmonial philosophy, Doyle’s Spiritualist rhetoric likely sounded familiar to his Mormon audience.[For a discussion on the similarities between Swedenborgian and Mormon eschatology seeL @DeathinSpiritualismandMormonism, 61] Doyle recognized many of these similarities, as I discuss when I examine his chapter of *Our Second American Adventure* titled “the Mormons,” and he may have chosen to visit Salt Lake City particularly because he believed his philosophy would resonate with its Mormon residents.

After the *Tribune* emphasizes that the growth, progress, and justice is characteristic of Doyle’s spirit world, it turns its attention to Doyle’s spirit photographs. Doyle’s psychical photographs accomplished two goals: they helped draw in a crowd and reinforced the idea that Spiritualism and Mormonism hold a common belief in an anthropocentric afterlife. Material culture such as the planchette and Ouija board had a strong role in the spread of Spiritualism as it promised an accessible way to engage in Spiritualist practice, was easily commodified, and drew sensationalist attention. [Urban notes that the planchette was introduced to the United States in 1858 and that their most popular manufacturer, Kirby & Company, reported selling over two hundred thousand units in the first year alone. @NewReligiousMovements, 76] Doyle’s spirit photographs likely played a similar role in helping draw a crowd in his Salt Lake City lecture. The photographs also operated to show similarities between Spiritualism and Mormonism as they provided evidence of spirits’ ability to maintain form in the afterlife, “the majority say no ‘traveler ever returns.’”[@ProofsAdvanced] Michael Homer notes that many Mormons did indeed receive visions of the dead, but claims that few had these experiences and that most of these occasions were in uncontrolled circumstances.[@HomerSpirAndMorm, 172. Homer continues that Mormons never conducted seances or took spirit photography seriously.] While Spiritualism and Mormonism may have had cosmological similarities that were more closely paralleled in the past, there seems to be a widening gap between the two religions interest in spirit photography and other empirical evidence of the afterlife. 

However, the *Tribune* notes that these spirit photographs were not the main focus of Doyle’s presentation, and suggests that Doyle himself focused mainly on the philosophical aspect of his lecture. The paper reports that:

>These pictures, impressive as they were, were not less convincing than the self-evident sincerity and earnestness of the lecturer himself, who sought by logic, patent facts, and plain deduction to make clear to his auditors that his message was one of cheer and uplift, calculated to inspire and help.[@ProofsAdvanced]

\noindent Neither Doyle nor his predominantly Mormon audience seemed to see spirit photography as the primary point of importance in his lecture. Although spirit photographs drew many people to Doyle’s lectures and were central to many newspapers reporting on his tour, he downplayed their importance and instead aimed to focus on a religious restoration centered around a return to an acceptance of mediumship. 

The *Tribune*’s report of Doyle’s lecture also focuses on his presentation of Spiritualism as a supplement to other religious beliefs. Doyle claims Spiritualism will “strengthen the base of all religion,” through providing proof of life after death.[@ProofsAdvanced] This echoes previous lectures made by Doyle where he stressed the universal application of Mediumship. In a lecture from his 1923 tour titled “Spiritualism and Psychic Photographs,” Doyle addressed similar topics to those covered by the *Tribune* including: the relationship between Spiritualism and other religions, the proof Spiritualism provides of the afterlife, and the individual and social progress that Spiritualism promises. When Doyle addressed the relationship between Spiritualism and other religions in this lecture, he emphasized:

>We [Spiritualists] are not against any other religion. Our knowledge is for all the world. We say to all, this is what we have discovered… Add it to the religion you already have, and you will find that religion all the better. If you have no religion then here is one which you can examine for yourself.[@PhotographLecture]

\noindent Although Doyle had levelled plenty of critiques against the Mormon Church in *A Study in Scarlet* and remained critical of Mormonism in *Our Second American Adventure*, his lecture in Salt Lake City presented Spiritualism as complementary to Mormonism. He did not portray the spirit world as exclusive to any particular group and presented a kind of universalism in that one from any kind of religious background can possess knowledge of the hereafter. Doyle was not reliant on individuals being convinced by his spirit photographs, but instead aimed to find ways Spiritualism could supplement belief in the afterlife. 

The *Tribune* then provides a synopsis of how Doyle came to accept Spiritualism and quotes him criticizing his materialist critics for refusing to properly investigate Spiritualism. The article notes how Doyle had previously been pronouncedly materialistic and had only come to accept Spiritualism after years of patient investigation.[@ProofsAdvanced] After the *Tribune* again notes the antagonism Doyle persistently faced from “the churches” it provides an excerpt from Doyle’s presentation in which he declared that most who support Spiritualism have devoted years to researching the topic whereas most skeptics write “without investigation and with prejudice in their hearts.”[@ProofsAdvanced] In these statements, Doyle drew a distinction between supporters of Spiritualism, who have taken the time to investigate psychical phenomena, and its antagonists, who attack Spiritualism with implicit biases and without evidence. While Spiritualism’s detractors might focus on fraudulence in physical evidence, such as spirit photographs, Doyle once again shifted discussion toward a different kind of “proof.”

As he proceeded, Doyle referred to his own experiences communicating with his deceased family members through mediumship to validate the truth of Spiritualism. The *Tribune* continues: 

>When my mother, dead years ago, and my brother and my son, both of whom lost their lives in the war, appear to me through a medium and tell me things the medium had no means of knowing, it is part of the argument that no man who does not investigate has the means to gainsay.[@ProofsAdvanced]

\noindent Doyle implies that spirit proofs can be verified through individual’s own personal connections with the spirit world, something that physical evidence cannot capture. In his “Spiritualism and Psychical Photographs” lecture notes, Doyle continues this argument, stating that spiritual knowledge is possible, “because I’ve experienced it… I have heard them and I have seen them…There are thousands and tens of thousands in all nations who have had the same experience.”[@PhotographLecture] By calling attention to World War One, Doyle evokes thousands of testimonials affirming spirit communication act as evidence of the existence of the spirit world. In so doing, he shifts the burden of denying these experiences to his materialist and church detractors. 

Doyle also used of others’ experiences reconvening with the dead to validate his spirit photographs. The *Tribune* mentions that Doyle was not able to showcase ectoplasm, “the connecting link between the world and the spirit realm,” in the Tabernacle because it is soluble in light.[@ProofsAdvanced]  Instead of providing his audience with their own experience with psychical phenomena, Doyle showcased spirit photographs that others’ have recognized the departed in. Among these photographs, he  included his famed photograph of spirits surrounding the Cenotaph monument. Doyle affirmed that thirty of these spirits had been positively recognized by friends or family.[@ProofsAdvanced] In so doing, he not only showcased physical evidence of psychical phenomena, but also referenced a religious connection that others have had with the piece. The proof is less so in the photograph than in the testimony of those who remain connected to the dead featured in it.

As the *Tribune* concludes its coverage of Doyle’s presentation, it notes an air of optimism in his speech and reiterates his universalist views. The article states that Doyle holds as a rule that humanity is more deserving of compassion than punishment and that “there is not as much evil in the world as theologians would have one believe."[@ProofsAdvanced]  Rather than conventional Christian views, Doyle expressed an anthropology and cosmology that was focused on human progress and development. The Tribune provides a quotation from Doyle: “one finds really little of pure evil in the world. The spirits that are evil will be retarded, but they, too, will have opportunity to go on as they grow into love.”[@ProofsAdvanced]  Rather than focusing on popular theological language concerning original sin or human degradation, Doyle presented the idea that humans can continue to improve themselves and impact their salvation into the afterlife.[This idea is also referenced in Doyle's interview with the *LA Times* “When one dies he reaches a stage just higher than that in which he exists on earth. And from that stage he shall pass to a higher sphere, and then on to another. It is a process of transmigration, you know.” @ShadesinTown]  In the spirit world, human growth and progress are not only possible, but are central concerns and uninhibited by the constraints of the physical world. Doyle’s view of human progress in the spirit world can be seen as a reaction to conventional Christian teachings that one’s salvation cannot be affected after death. 

In closing his lecture by questioning the validity of mainstream Christian theologians, Doyle again brought attention to the difference between Spiritualism and more institutionalized religions. As he referred to “boundaries breaking down between the seen and unseen” in the *Telegram* and the pessimism of theologians in the *Tribune*, Doyle alluded to a broader critique of institutionalized Christianity and the intellectual hierarchy that informs theological decision-making. While Doyle applauded the Mormon Church’s eclecticism and openness toward new religious ideas, he also levelled criticisms towards their hierarchical priesthood for its control over communication with other worldly planes of existence. In this sense, Salt Lake City seemed to serve Doyle’s interest in showing how religious investigation and innovation could lead to a progressive and developed societies, while also allowing him the chance to illustrate how religious hierarchies could repress these developments. As I continue, I illustrate how Doyle more transparently conveys these ideas in his chapter of *Our Second American Adventure* titled “the Mormons.”

\allsectionsfont{\raggedright}
## Salt Lake City in *Our Second American Adventure*:

Doyle recorded his 1923 visit to Salt Lake City in a chapter of *Our Second American Adventure* titled, “the Mormons.” This travelogue was intended to promote Doyle’s Spiritualist views to a wide audience and Doyle provides a history of Mormonism that balances his sympathy with many of the religion’s tenets and its history of persecution with criticisms of its repressive priesthood and insularity. In the chapter, Doyle provides a minimal synopsis of his visit to Utah, focusing on the openness of the people to his message, the splendidness of their city, and the impressive architecture of the Salt Lake Tabernacle.[@DoyleSecondAdv, 88-89]  Doyle then shifts to focus on the teachings of Joseph Smith and the development of the Mormon Church for the rest of the chapter. While Doyle remains sympathetic with many of the tenets of Mormonism, focusing largely on their overlap with Spiritualist tenets, he questions the legitimacy of Smith’s revelations and frequently presents the possibility of fabrication. Doyle ultimately concludes that Spiritualism can act to ameliorate the limitations enforced by the Mormon church hierarchy and restore Mormonism to its original Christian teachings.

In *Our Second American Adventure*, Doyle argues that Smith was potentially a medium and that many of his teachings are substantiated by Spiritualist findings. Doyle notes that both Smith and the Spiritualists declare that spirit itself is super fine matter, that true marriage carries on in the afterlife, and that the mind continues existing after death.[@DoyleSecondAdv, 87] Doyle sees the correlations between Spiritualist beliefs and Smith’s revelations as evidence of his legitimacy as a medium stating that they “coincide with spirit-information we ourselves have received.”[@DoyleSecondAdv, 101]  In so doing, Doyle privileges the truth of his own findings as a Spiritualist over Smith’s revelations and uses these findings as a litmus test to judge the quality of his “mediumship.”

However, Doyle also questions the legitimacy of Smith’s teachings by focusing on historical discontinuities. Among these, Doyle states there is a lack of evidence concerning the arrival of the Lamanites in America in 600 BCE and claims that Moroni’s spiritual gifts are given in the words of Paul.[@DoyleSecondAdv, 103] After problematizing the Mormon narrative, Doyle continues, “that Smith was a true medium, but that his controls were not always reliable, nor did he have sufficient character to check them as they should be checked.” [@DoyleSecondAdv, 103] Doyle acknowledges a degree of cohesiveness to the Book of Mormon, that Smith’s revelations were witnessed, and that the degree of detail to Smith’s narrative would be difficult to fabricate. However, he ultimately argues that Mormonism is either a fraudulent fabrication or that, “Joseph Smith had a record, as is vouched for by so many, and that he worked into it his own religious memories and conceptions.”[@DoyleSecondAdv, 101]  Doyle is implying that there is good evidence behind many of Smith’s revelations and he was most likely a medium to some extent, but much of Smith’s teachings seem unsubstantiated and drawn from a variety of religious traditions.

As Doyle gives his summary of Smith’s history, he presents an eclectic array of religious traditions that Mormonism references, noting that his revelations echo Swedenborg and Davis, that Urim and Thummin are drawn from Jewish texts, and that American Indians are seen as descended from the Lamanites. While Doyle is skeptical about the legitimacy of the account he presents, he does note that “the ultimate result has been to produce as decent a law-abiding community as is to be found at present in any part of the world.”[@DoyleSecondAdv, 103]  By beginning and ending his chapter with Mormon society’s exceptional progress, Doyle presents Mormonism’s eclecticism as bringing positive social benefits, while also attempting to problematize the Church’s scriptural body. 

Doyle also echoes criticisms made of Mormon society in *A Study in Scarlet*, by continuing to criticize Mormonism’s hierarchical priesthoods and antagonism towards other religious communities. While he begins his chapter on “The Mormons” by praising their splendid city and their tolerance, he quickly reminds the audience of the insularity of their community, noting that “The huge temple, to which none but Mormons are admitted, did not interest me much.”[@DoyleSecondAdv, 89] In expressing his lack of interest in the exclusive Salt Lake Temple, Doyle asserts a lack of interest in affiliating himself with Mormon institutions, even as he affirms many of the religion’s tenets. Doyle also addresses what he sees as a decline in the church following Smith’s death:

>Instead of being a message of hope and knowledge for the whole human race such as we bring by Spiritualism, it [Mormonism] is tending towards the discredited and old-world idea of a special priestly caste, of formal sacraments, and of a new sect, complete in itself and antagonistic to the other sects. [@DoyleSecondAdv, 97]

\noindent This passage illustrates that Doyle is consistent in his criticisms toward hierarchical church organizations and sectarianism within the Christian community. He also explicitly ties the Mormon priesthood to polygamist practices, stating that edicts passed by the priesthood, “were responsible for polygamy, which had nothing whatever to do with the original teaching of Smith's revelation.”[@DoyleSecondAdv, 97] Doyle description of Mormon organization as reflecting “old-world ideas” that have been “discredited” by newer religions such as Spiritualism creates a distinction between regressive and uncivilized ideas and the new innovations of Spiritualism.  Doyle frames Mormonism as attached to the same “old-world” ecclesiology and liturgy as Catholicism and Protestantism. On the other hand, Spiritualism is what actually offers a restorative path to primitive Christianity.

Doyle continues to differentiate between the innovations of Spiritualism and the regressive inhibitions of Mormonism by expressing his sympathies with the Mormon idea of continuous revelation, while arguing that cases of continuous revelation should be understood as a kind of mediumship. He suggests that Mormon history and ideas would be more accurately understood with Spiritualist knowledge. In *Our Second American Adventure*, Doyle writes highly of Joseph Smith’s revelations, but presents them as a kind of mediumship: 

>I think that if the Mormons understood the philosophy of Spiritualism, and if they considered the possibility of Smith, their founder, being a strong medium, they would be able to get a connected and reasonable explanation of all that occurred, which would in no way detract from its dignity or other-world origin. [@DoyleSecondAdv, 87-88]

\noindent Doyle interprets the Mormon doctrine of continuous revelation as equivalent to mediums’ spirit communication, leading him to accept it. In so doing, Doyle again voices his sympathy for Mormon beliefs and values, but presents Spiritualism as having a more developed and modern understanding and explanation of the world.

Doyle also suggests Spiritualism has a more developed approach to communication with the other worldly. He argues that this communication with the spirit world has been abandoned by mainstream Christian institutions, but is being recovered by new religions. He sees Spiritualism and Mormonism as sharing the same message, that “Christian creeds had wandered far away from primitive spiritual truths […] ritual and forms have completely driven out that direct spirit–communion and power which are the real living core of religion.”[@DoyleSecondAdv, 92] By extolling spirit communication, Mormonism and Spiritualism both capture a perennial religious truth with historical authority. However, Doyle argues that Spiritualism also carries the positive qualities of modernity, providing a more developed and accurate knowledge of what spirit communication is. While Smith was limited to one case of spirit communication, Spiritualists have had a “far wider experience” and have been able to “systematize and compare many examples of what to Smith was an isolated miracle.” [@DoyleSecondAdv, 92] In comparing Spiritualism and Mormonism, Doyle praises both for their ability to encourage communication with the other worldly, but Spiritualism is shown to provide a developed and scientific understanding of this perennial knowledge rather than a rely on limited accounts of spirit communication that are controlled by a church hierarchy. 
In concluding his chapter on Mormonism in *Our Second American Adventure*, Doyle defends Mormonism, taking note of the sensationalized accounts of the religion that the British Press has given. He acknowledges the newness of Mormonism and condemns the religious mainstream in Britain for its intolerance of new religious beliefs. He makes a point of addressing the civility of Mormons by sharing a defense of Mormon society that has been written by non-Mormon visitors:

>As to the relations between the Gentiles and Mormons in Utah, I have a document before me signed by all the representative Gentiles, many of them British, which says, “We denounce as absolute lies the charges against the Mormons of sexual immorality, or murder or other depravity, or of tyrannous control in the fields of religion, commerce, morals, or society, and we protest against a continuance of this unfounded and wicked propaganda." This should be noted by a certain section of the British Press.[@DoyleSecondAdv, 103-204] 

\noindent Doyle’s denouncement of the British press creates a distance between his own work and other sensationalized depictions of Mormon society. Doyle depicts members of the British press as promoting “propaganda” that misrepresent new religions, like Mormonism and Spiritualism. By calling attention to sensationalism in the press, he problematizes popular attacks on Spiritualism. If the press publishes misinformation about the history of Mormon society, lies concerning the validity of medium also risk the possibility of being published.

Despite this attack, Doyle also defends *A Study in Scarlet* even though he relied on similiar misinformation to inform the novel. In *Our Second American Adventure*, Doyle wrote that he refused to address sensationalism in A Study in Scarlet while in Utah, because “the facts were true enough, though there were many reasons which might extenuate them.”[@DoyleSecondAdv, 87]  Though *A Study in Scarlet* inaccurately depicted the Danites as pervasive and active force in Mormon society, Doyle did not denounce his own work as full of “unfounded and wicked propaganda.” While in Utah, Doyle seemed committed to the idea that the inaccuracies in the novel were insignificant and served a role in creating a fictional setting. Doyle was asked to express his regrets about spreading misinformation by George H. Higgins, a non-Mormon physician. In response he wrote:

>All I said about the Danite Band and the murders is historical so I cannot withdraw that tho [sic], it is likely that in a work of fiction it is stated more luridly than in a work of history. It's best to let the matter rest.[@HigginsMay10]

\noindent While Doyle sought to address the misinformation about Mormonism that was spread by the British press, he was not interested in bringing his own sensationalism any further attention. He utilized his position as a writer of fiction to provide justification for his depiction of Mormon society and tried to present himself sympathetic with Mormon society. 

In his final statement concerning Mormonism in *Our Second American Adventure*, Doyle reiterates his sympathy with Mormonism and asks for reciprocity from his Mormon audience. He directly addresses the Mormon reader, stating that his analysis of Mormonism, “may perhaps induce some Mormon scholar to take up psychic matters and to check my observations from his own point of view.” [@DoyleSecondAdv, 104] While Doyle takes a stance critical of Mormonism and privileges the truth of Spiritualist conclusions, he asks the Mormon reader to supplement their religion with knowledge of psychical phenomena. Doyle continues,

>It seems to me that such a line of thought may help such men to understand the real origin of their own movement without in any way derogating from its essential truth. It may also serve as a warning against the indiscriminate adoption of supposed revelations, which, in the case of polygamy, have done so much harm to the movement. [@DoyleSecondAdv, 104. (Emphasis added).] 

\noindent Spiritualism is presented as more than a supplement to Mormonism, but as one that can restore the religion from its “real origin” by distancing it from the control of a hierarchical priesthood. Doyle presents the social degradation that this form of hierarchy brings through once again turning to Mormon polygamous practices. This kind of social decline can only be avoided if individuals turn back to the primitive Christian basis on which Mormonism was founded by adopting Spiritualist beliefs. In Doyle's eclectic view of history, progress requires looking both forward and backward, structuring religious hierarchies on a pure and primitive Christianity which is unveiled through a modern understanding of psychical phenomena. 

\newpage

# Works Cited


